import { Metadata } from 'next';
import { siteConfig } from '@/lib/site';

export const metadata: Metadata = {
  title: siteConfig.name,
  description: siteConfig.description,
  keywords: [
    // TIER 1: Palavras-chave de ULTRA ALTO VOLUME (5M+ buscas/mês)
    // Baseado nos dados reais do Google Ads
    'GTA 6',
    'GTA 5',
    'GTA 6 release date',
    'GTA VI',
    
    // TIER 2: Palavras-chave de ALTO VOLUME (500K+ buscas/mês)
    // Dados confirmados pelo Google Ads
    'GTA 6 map',
    'GTA 6 price',
    'GTA 6 trailer',
    'GTA Online',
    'Rockstar Games',
    'Take-Two',
    'Vice City',
    'when is GTA 6 coming out',
    
    // TIER 3: Palavras-chave de MÉDIO-ALTO VOLUME (50K+ buscas/mês)
    // Confirmadas com dados reais de busca
    'Grand Theft Auto 5',
    'Grand Theft Auto 6',
    'GTA 6 characters',
    'GTA 6 gameplay',
    'GTA 6 leaks',
    'GTA 6 news',
    'GTA 6 on PS5',
    'GTA 6 online',
    'GTA 6 PC',
    'GTA 6 PC release date',
    'GTA 6 PC requirements',
    'GTA 6 pre order',
    'GTA 6 PS5',
    'GTA 6 system requirements',
    'Jason GTA 6',
    'Liberty City',
    'Lucia GTA 6',
    'PS5 Pro enhanced games',
    'will GTA 6 be on PC',
    
    // TIER 4: Palavras-chave de MÉDIO VOLUME (5K+ buscas/mês)
    // Com base nos dados do Google Ads
    'GTA 6 announcements',
    'GTA 6 features',
    'GTA 6 FPS',
    'GTA 6 game',
    'GTA 6 graphics',
    'GTA 6 leaked gameplay',
    'GTA 6 leaked gameplay footage',
    'GTA 6 leaked map',
    'GTA 6 location',
    'GTA 6 main characters',
    'GTA 6 map size',
    'GTA 6 mods',
    'GTA 6 platforms',
    'GTA 6 protagonists',
    'GTA 6 setting',
    'GTA 6 story',
    'GTA 6 system requirements PC',
    'GTA 6 updates',
    'GTA 6 vehicles',
    'Leonida GTA 6',
    'Lucia and Jason',
    'PS5 Pro GTA 6',
    'Take-Two Interactive GTA 6',
    'what city is GTA 6 based on',
    
    // TIER 5: Palavras-chave de BAIXO-MÉDIO VOLUME (500-5K buscas/mês)
    // Dados confirmados pelo Google Ads
    'buy GTA 6',
    'Bonnie and Clyde GTA 6',
    'Cal Hampton GTA 6',
    'can my PC run GTA 6',
    'GTA 6 cars list',
    'GTA 6 cheats',
    'GTA 6 editions',
    'GTA 6 graphics comparison',
    'GTA 6 missions',
    'GTA 6 official',
    'GTA 6 official trailer',
    'GTA 6 official trailer 2',
    'GTA 6 on Xbox Series X',
    'GTA 6 PC launch',
    'GTA 6 performance',
    'GTA 6 price prediction',
    'GTA 6 PS5 gameplay',
    'GTA 6 rumors',
    'GTA 6 special edition',
    'GTA 6 story mode',
    'GTA 6 trailer breakdown',
    'GTA 6 weapons',
    'how big will the GTA 6 map be',
    'how to play GTA 6 early',
    'is GTA 6 coming to PS4',
    'latest GTA 6 news',
    'Liberty City GTA 6',
    'Raul Bautista GTA 6',
    'Real Dimez GTA 6',
    'Roxy GTA 6',
    'where to buy GTA 6',
    'who are the main characters in GTA 6',
    
    // TIER 6: Palavras-chave de BAIXO VOLUME (50-500 buscas/mês)
    // Nicho específico com baixa concorrência
    'Bae-Luxe GTA 6',
    'Boobie Ike GTA 6',
    'Boobie Ike Vice City',
    'Dre\'Quan Priest GTA 6',
    'GTA 6 character leaks',
    'GTA 6 community',
    'GTA 6 confirmation',
    'GTA 6 console performance',
    'GTA 6 fan theories',
    'GTA 6 gameplay mechanics',
    'GTA 6 leaks explained',
    'GTA 6 map details',
    'GTA 6 missions list',
    'GTA 6 news update',
    'GTA 6 price speculation',
    'GTA 6 release date speculation',
    'GTA 6 rumored features',
    'GTA 6 source code leak',
    'GTA 6 speculation',
    'GTA 6 streaming',
    'GTA 6 Twitch',
    'GTA 6 vs GTA 5 graphics comparison',
    'GTA 6 walkthrough',
    'latest GTA 6 leaks',
    'Leonida state GTA 6',
    'new features in GTA 6',
    'new GTA 6 rumors',
    'Only Raw Records GTA 6',
    'Rockstar Games GTA 6 news',
    'what is the story of GTA 6',
    
    // TIER 7: Palavras-chave Long-tail e Específicas
    // Menor volume mas alta relevância para SEO
    'GTA 6 official announcements',
    'GTA 6 reveal trailer analysis',
    'GTA 6 main characters Lucia and Jason',
    'GTA 6 Vice City map details',
    'what to expect from GTA 6 gameplay',
    'GTA 6 story plot predictions',
    'GTA 6 vehicles customization options',
    'GTA 6 weapons arsenal',
    'GTA 6 weapons list and features',
    'GTA 6 graphics comparison PS5 vs PC',
    'GTA 6 performance on consoles',
    'GTA 6 performance issues and fixes',
    '60fps GTA 6',
    'how to get 60fps in GTA 6',
    'GTA 6 Xbox Series X/S performance',
    'PS5 Pro enhanced GTA 6',
    'GTA 6 console performance',
    'best GTA 6 mods PC',
    'how to install GTA 6 mods',
    'GTA 6 modding',
    'GTA 6 beginner\'s guide for new players',
    'GTA 6 tips and tricks',
    'GTA 6 tips for new players',
    'GTA 6 cheats and secrets discovered',
    'GTA 6 mission walkthrough',
    'GTA 6 live stream gameplay reaction',
    'GTA 6 community reactions',
    'popular GTA 6 fan theories',
    'GTA 6 community fan theories',
    'why GTA 6 is important',
    'GTA 6 impact on gaming',
    
    // TIER 8: Personagens Secundários e Referências Ultra-específicas
    // Volume muito baixo mas zero concorrência
    'Cal Hampton GTA 6 character role',
    'Boobie Ike Vice City connections',
    'Dre\'Quan Priest GTA 6 music career',
    'Bae-Luxe and Roxy Real Dimez story',
    'Raul Bautista GTA 6 bank robbery',
    'Bonnie and Clyde inspiration in GTA 6',
    'Liberty City connection to GTA 6 characters',
    'Rockstar Games marketing strategy for GTA 6',
    'Take-Two Interactive GTA 6 development',
    'Only Raw Records GTA 6 reference',
    'Real Dimez GTA 6 characters',
    'Leonida state GTA 6 details',
    
    // TIER 9: Marca e Autoridade LeakerFlow
    // Específico para construção de autoridade
    'LeakerFlow',
    'LeakerFlow GTA 6',
    'LeakerFlow GTA 6 insights',
    'unconfirmed GTA 6 details',
    'latest GTA 6 information',
    'GTA 6 development updates',
    'latest news on Grand Theft Auto 6',
    
    // TIER 10: Variações e Sinônimos Estratégicos
    // Para cobertura semântica completa
    'GTA 6 official',
    'GTA 6 game',
    'Grand Theft Auto 5 vs GTA 6',
    'GTA Online integration with GTA 6',
    'male and female protagonist GTA 6',
    'Lucia and Jason GTA 6 characters',
    'Liberty City Lucia\'s origin',
    'GTA 6 platforms',
    'GTA 6 on PS4 and Xbox One',
    'GTA 6 guides',
    'GTA 6 walkthrough',
    'best GTA 6 streams',
    'GTA 6 YouTube gameplay',
    'GTA 6 discussions',
    'GTA 6 fan speculation',
    'GTA 6 character theories',
    'GTA 6 map leaks analysis',
    'GTA 6 leaked gameplay footage',
    'GTA 6 vehicles customization',
    'GTA 6 graphics comparison',
    'how to play GTA 6 early',
    'best GTA 6 mods',
    'GTA 6 cheats and secrets',
    'GTA 6 live stream gameplay',
    'GTA 6 streaming',
    'GTA 6 pre-order',
    'GTA 6 editions',
    'where to buy GTA 6',
  ],
  authors: [
    {
      name: 'LeakerFlow',
      url: 'https://leakerflow.com',
    },
  ],
  creator: 'LeakerFlow',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    description: siteConfig.description,
    creator: '@leakerflow',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

